name: black

on: [push, pull_request] 


jobs:
  black:
    name: Style Check with Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python_version: "3.8"
      - run: "python -m pip install black"
        name: Install black
      - run: "python -m black -l 99 --check ."
        name: Style checking with black
